import { Language, MenuItem, Review, FAQItem, Table } from "./types";

export const LANGUAGES: Language[] = [
  { code: "fr", name: "Français", flag: "🇫🇷" },
  { code: "en", name: "English", flag: "🇬🇧" },
  { code: "th", name: "ไทย", flag: "🇹🇭" },
  { code: "de", name: "Deutsch", flag: "🇩🇪" },
  { code: "es", name: "Español", flag: "🇪🇸" },
  { code: "it", name: "Italiano", flag: "🇮🇹" },
  { code: "pt", name: "Português", flag: "🇵🇹" },
  { code: "zh", name: "中文", flag: "🇨🇳" },
  { code: "ja", name: "日本語", flag: "🇯🇵" },
  { code: "ko", name: "한국어", flag: "🇰🇷" },
];

export const HERO_CAROUSEL_IMAGES = [
  {
    url: "https://images.unsplash.com/photo-1528127269322-539801943592?auto=format&fit=crop&w=1920&q=80",
    title: {
      fr: "Bangkok Éternelle",
      en: "Eternal Bangkok",
      th: "กรุงเทพมหานคร",
      de: "Ewiges Bangkok",
      es: "Bangkok Eterno",
      it: "Bangkok Eterna",
      pt: "Bangkok Eterna",
      zh: "永恒曼谷",
      ja: "永遠のバンコク",
      ko: "영원한 방콕",
    },
    subtitle: {
      fr: "L'énergie vibrante des nuits siamoises et des temples sacrés.",
      en: "The vibrant energy of Siamese nights and sacred temples.",
      th: "พลังงานอันมีชีวิตชีวาของค่ำคืนสยามและวัดศักดิ์สิทธิ์",
      de: "Die pulsierende Energie siamesischer Nächte und heiliger Tempel.",
      es: "La energía vibrante de las noches siamesas y los templos sagrados.",
      it: "L'energia vibrante delle notti siamesi e dei templi sacri.",
      pt: "A energia vibrante das noites siamesas e dos templos sagrados.",
      zh: "暹罗之夜与神圣寺庙的活力。",
      ja: "シャムの夜と神聖な寺院の活気溢れるエネルギー。",
      ko: "시암의 밤과 신성한 사원의 활기찬 에너지.",
    },
  },
  {
    url: "https://images.unsplash.com/photo-1552465011-b4e21bf6e79a?auto=format&fit=crop&w=1920&q=80",
    title: {
      fr: "Wat Arun & Sérénité",
      en: "Wat Arun & Serenity",
      th: "วัดอรุณราชวราราม",
      de: "Wat Arun & Gelassenheit",
      es: "Wat Arun y Serenidad",
      it: "Wat Arun & Serenità",
      pt: "Wat Arun & Serenidade",
      zh: "黎明寺与宁静",
      ja: "ワット・アルンと静寂",
      ko: "왓 아룬과 고요함",
    },
    subtitle: {
      fr: "L'éclat majestueux du Temple de l'Aube sur la rivière Chao Phraya.",
      en: "The majestic glow of the Temple of Dawn on the Chao Phraya River.",
      th: "ความงดงามตระการตาของวัดอรุณเหนือแม่น้ำเจ้าพระยา",
      de: "Der majestätische Glanz des Tempels der Morgenröte auf dem Chao Phraya Fluss.",
      es: "El brillo majestuoso del Templo del Amanecer sobre el río Chao Phraya.",
      it: "Il maestoso splendore del Tempello dell'Alba sul fiume Chao Phraya.",
      pt: "O brilho majestoso do Templo do Amanhecer no rio Chao Phraya.",
      zh: "昭披耶河畔黎明寺的神圣余晖。",
      ja: "チャオプラヤー川に佇む暁の寺の壮大な輝き。",
      ko: "짜오프라야 강 위의 새벽 사원의 웅장한 빛.",
    },
  },
  {
    url: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=1920&q=80",
    title: {
      fr: "La Haute Gastronomie Thaïe",
      en: "Fine Thai Gastronomy",
      th: "อาหารไทยระดับพรีเมียม",
      de: "Feine Thailändische Gastronomie",
      es: "Alta Gastronomía Tailandesa",
      it: "Alta Gastronomia Thailandese",
      pt: "Alta Gastronomia Tailandesa",
      zh: "泰式高端美食",
      ja: "極上のタイ美食",
      ko: "파인 타이 가스트로노미",
    },
    subtitle: {
      fr: "Des créations artistiques mêlant herbes impériales et recettes familiales.",
      en: "Artistic creations blending imperial herbs and family heritage.",
      th: "การสร้างสรรค์งานศิลปะจากสมุนไพรชาววังและสูตรอาหารของครอบครัว",
      de: "Künstlerische Kreationen, die kaiserliche Kräuter und Familienerbe verbinden.",
      es: "Creaciones artísticas que mezclan hierbas imperiales y recetas familiares.",
      it: "Creazioni artistiche che fondono erbe imperiali e ricette di famiglia.",
      pt: "Criações artísticas misturando ervas imperiais e receitas de família.",
      zh: "融合宫廷草药与家族传承的艺术创作。",
      ja: "宮廷のハーブと家伝のレシピが織りなす芸術的な一皿。",
      ko: "왕실 허브와 가문 비법이 조화를 이룬 예술적 예술작.",
    },
  },
];

export const LORE_TEXT = {
  fr: {
    title: "Notre Histoire — THE FAMILY",
    storyLines: [
      "Fondé par la lignée culinaire Chatsuwan originaire de Chiang Mai, THE FAMILY est l'aboutissement de trois générations passionnées par l'art du goût thaïlandais.",
      "Notre restaurant réinvente l'hospitalité légendaire du pays du sourire au cœur d'un dôme luxueux d'inspiration végétale. Chaque matin, nos herbes impériales, galanga, piments nains et feuilles de pandan sont inspectés individuellement pour garantir une palette gustative vibrante.",
      "Nous croyons en une cuisine d'émotions, où les dîners privés se transforment en rituels royaux. Bienvenue dans notre famille.",
    ],
  },
  en: {
    title: "Our Story — THE FAMILY",
    storyLines: [
      "Founded by the Chatsuwan culinary legacy from Chiang Mai, THE FAMILY represents three generations of passionate dedication to authentic Thai flavor.",
      "Our dining room fuses the legendary hospitality of the Land of Smiles with a luxurious tropical botanical oasis. Every morning, our fresh lemongrass, galangal, bird's eye chilies, and sweet lime leaves are inspect for raw structural perfection.",
      "We build an emotive table where guest interactions become sacred culinary rituals. Welcome to our family.",
    ],
  },
  th: {
    title: "เรื่องราวของเรา — เดอะ แฟมิลี่",
    storyLines: [
      "ก่อตั้งขึ้นโดยมรดกทางอาหารของตระกูล ชัชสุวรรณ จากเชียงใหม่ THE FAMILY คือจุดสูงสุดของความหลงใหลในศิลปะรสชาติไทยกว่าสามรุ่น",
      "ร้านของเราสร้างนิยามใหม่ให้กับการต้อนรับอันเป็นตำนานของเมืองยิ้ม ภายใต้การตกแต่งสไตล์สวนเขตร้อนที่หรูหรา ทุกเช้า สมุนไพรชาววัง ข่า พริกขี้หนู และใบเตยจะได้รับการคัดสรรทีละใบเพื่อรับประกันรสชาติที่แท้จริงมีชีวิตชีวา",
      "เราเชื่อในอาหารที่ถ่ายทอดอารมณ์ความรู้สึก ที่ซึ่งการรับประทานอาหารกลายเป็นพิธีกรรมอันศักดิ์สิทธิ์ ยินดีต้อนรับสู่ครอบครัวของเรา",
    ],
  },
};

export const MENU_ITEMS: MenuItem[] = [
  {
    id: "pad_thai",
    name: {
      fr: "Pad Thaï Impérial",
      en: "Imperial Pad Thai",
      th: "ผัดไทยจักรพรรดิ",
      de: "Kaiserliches Pad Thai",
      es: "Pad Thai Imperial",
      it: "Pad Thai Imperiale",
      pt: "Pad Thai Imperial",
      zh: "皇家泰式炒河粉",
      ja: "御料パッタイ",
      ko: "임페리얼 팟타이",
    },
    description: {
      fr: "Nouilles de riz croustillantes sautées au tamarin bleu, crevettes tigrées géantes grillées et pousses de soja biologiques.",
      en: "Crispy rice noodles wok-tossed with blue tamarind juice, grilled giant tiger prawns, and organic bean sprouts.",
      th: "เส้นจันท์เหนียวนุ่มผัดซอสมะขามสูตรโบราณ เสิร์ฟพร้อมกุ้งลายเสือย่างถ่านและถั่วงอกออร์แกนิก",
      de: "Knusprige Reisnudeln im Wok geworfen mit blauem Tamarindensaft, gegrillten Riesen-Tigergarnelen und Bio-Sojasprossen.",
      es: "Fideos de arroz crujientes salteados en salsa de tamarindo, langostinos tigre gigantes a la parrilla y brotes de soja orgánicos.",
      it: "Tagliolini di riso saltati al wok con succo di tamarindo, gamberi tigre giganti grigliati e germogli di soia biologici.",
      pt: "Massa de arroz salteada com suco de tamarindo, camarões tigre gigantes grelhados e brotos de feijò orgânicos.",
      zh: "秘制罗望子酱爆炒河粉，配烤珍宝老虎虾及有机豆芽。",
      ja: "極上タマリンドソースで炒めた米粉麺コシがあり、厳選大虎海老の炭火焼きを添えて。",
      ko: "블루 타마린드 소스로 볶아낸 최고급 쌀국수, 석쇠에 구운 타이거 왕새우와 유기농 숙주나물 곁들임.",
    },
    price: 28,
    image: "https://images.unsplash.com/photo-1626804475315-96440c9bc353?auto=format&fit=crop&w=800&q=80",
    isSpicy: false,
    tags: ["all", "non-spiced", "seafood", "chicken"],
  },
  {
    id: "tom_yum",
    name: {
      fr: "Soup Tom Yum Royale",
      en: "Royal Tom Yum Soup",
      th: "ต้มยำกุ้งน้ำข้นโบราณ",
      de: "Königliche Tom Yum Suppe",
      es: "Sopa Tom Yum Real",
      it: "Zuppa Tom Yum Reale",
      pt: "Sopa Real Tom Yum",
      zh: "皇家冬阴功汤",
      ja: "宮廷トムヤムクン",
      ko: "로열 똠얌꿍 수프",
    },
    description: {
      fr: "Bouillon acidulé parfumé et infusé à la citronnelle sauvage, galanga, champignons sauvages et pinces de homard.",
      en: "Tangy and aromatic broth infused with wild lemongrass, galangal, fresh wild mushrooms, and elegant lobster claws.",
      th: "ต้มยำกุ้งแม่น้ำน้ำข้นรสจัดจ้าน หอมกลิ่นตะไคร้ป่า ข่าแก่ ใบมะกรูด และเห็ดป่า คัดสรรพิเศษ",
      de: "Säuerliche, aromatische Brühe infused mit wildem Zitronengras, Galgant, Waldpilzen und luxuriösen Hummerscheren.",
      es: "Caldo picante y aromático con limoncillo silvestre, galanga, champiñones frescos y pinzas de langosta real.",
      it: "Brodo piccante e acidulo infuso di lemongrass selvatico, galanga, funghi freschi e chele di astice.",
      pt: "Caldo picante e perfumado com capim-limão selvagem, galanga, cogumelos frescos e pinças de lagosta.",
      zh: "野生香茅、南姜、鲜菇与顶级龙虾螯精心熬制的浓郁酸辣御汤。",
      ja: "野生レモングラス、ガランガル、厳選キノコ、贅沢なロブスターの爪から煮出した極上の酸辣スープ。",
      ko: "야생 레몬그라스, 갈랑갈, 버섯과 신선한 로브스터 바닷가재 집게살을 우려내어 시원하고 매콤한 황실 수프.",
    },
    price: 32,
    image: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=800&q=80",
    isSpicy: true,
    spicyLevel: 2,
    tags: ["all", "spiced", "seafood"],
  },
  {
    id: "green_curry",
    name: {
      fr: "Curry Vert aux Herbes de Chiang Mai",
      en: "Chiang Mai Green Curry",
      th: "แกงเขียวหวานไก่พรีเมียม",
      de: "Chiang Mai Grünes Curry",
      es: "Curry Verde de Chiang Mai",
      it: "Curry Verde di Chiang Mai",
      pt: "Caril Verde de Chiang Mai",
      zh: "清迈生磨绿咖喱",
      ja: "チェンマイ特製グリーンカレー",
      ko: "치앙마이 수제 그린 커리",
    },
    description: {
      fr: "Lait de coco pressé par nos soins, herbes écrasées au mortier, blanc de poulet fermier et aubergines thaïes.",
      en: "House-pressed coconut milk, hand-mortared green herbs, pasture-raised organic chicken breast, and local Thai eggplants.",
      th: "แกงเขียวหวานพริกแกงตำมือสูตรเชียงใหม่ รสละมุนด้วยน้ำกะทิคั้นสด อกไก่บ้านเหนียวนุ่ม และมะเขือเปราะใบโหระพา",
      de: "Hausgepresste Kokosmilch, von Hand gemörserte grüne Kräuter, Hühnerbrust aus Freilandhaltung und thailändische Auberginen.",
      es: "Leche de coco fresca, hierbas machacadas en mortero, pechuga de pollo de granja y berenjenas tailandesas miniatura.",
      it: "Latte di cocco pressato a freddo, erbe fresche pestate al mortaio, petto di pollo ruspante e melanzane tailandesi.",
      pt: "Leite de coco caseiro, ervas verdes moídas no almofariz, peito de frango do campo e berinjelas tailandesas.",
      zh: "手工研磨青草药绿咖喱，融入鲜榨浓郁椰浆、走地鸡胸肉与特产泰式小圓茄。",
      ja: "手擂りの生ハーブペースト、搾りたての無添加ココナッツミルク、地鶏の胸肉、新鮮なタイ丸茄子のマリアージュ。",
      ko: "매일 아침 수제로 짠 유기농 코코넛 밀크와 절구로 빻은 그린 허브, 부드러운 방목 닭가슴살과 타이 가지.",
    },
    price: 26,
    image: "https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?auto=format&fit=crop&w=800&q=80",
    isSpicy: true,
    spicyLevel: 2,
    isGlutenFree: true,
    tags: ["all", "spiced", "chicken", "gluten-free"],
  },
  {
    id: "red_curry",
    name: {
      fr: "Curry Rouge au Bœuf Wagyu",
      en: "Wagyu Beef Red Curry",
      th: "แกงเผ็ดเนื้อวากิวพรีเมียม",
      de: "Rotes Curry mit Wagyu-Rind",
      es: "Curry Rojo de Buey Wagyu",
      it: "Curry Rosso con Manzo Wagyu",
      pt: "Caril Vermelho de Carne Wagyu",
      zh: "和牛肉红咖喱",
      ja: "和牛レッドカレー",
      ko: "와규 소고기 레드 커리",
    },
    description: {
      fr: "Lamelles de filet de bœuf Wagyu A5 fondues dans une sauce crémeuse au curry rouge de Kaeng Phet, litchis et piment doux.",
      en: "Melt-in-mouth beef Wagyu A5 slices stewed in a rich, creamy Kaeng Phet red curry sauce, sweet lychee, and baby red peppers.",
      th: "แกงเผ็ดเนื้อวากิวลายหินอ่อนระดับ A5 ละลายในปาก เคี่ยวในพริกแกงแดงสูตรเข้มข้น ผลลิ้นจี่สด และใบมะกรูดซอย",
      de: "Zartes Wagyu-Rind A5 in cremiger roter Kaeng-Phet-Currysauce mit Litschis und mildem roten Chili.",
      es: "Filetes de buey Wagyu A5 derretidos en salsa cremosa de curry rojo Kaeng Phet, lichi dulce y pimiento rojo.",
      it: "Fettine di manzo Wagyu A5 cotte in salsa cremosa al curry rosso Kaeng Phet, litchi freschi e peperone dolce.",
      pt: "Beef Wagyu A5 fatiado guisado em molho cremoso de caril vermelho Kaeng Phet, lichia e pimentos doces.",
      zh: "入口即化的高级A5和牛片，煮至酥软并浸润在红咖喱中，缀以荔枝清香与鲜辣椒。",
      ja: "口に中でとろける極上A5和牛、ライチの果実、甘いパプリカを合わせ煮込んだ最高にリッチなレッドカレー赤肉香る一品。",
      ko: "입안에서 부드럽게 녹아내리는 최고 등급 와규 A5 소고기 슬라이스, 달콤한 리치와 매콤달콤한 레드 커리의 조화.",
    },
    price: 38,
    image: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=800&q=80",
    isSpicy: true,
    spicyLevel: 1,
    isGlutenFree: true,
    tags: ["all", "spiced", "beef", "gluten-free"],
  },
  {
    id: "som_tam",
    name: {
      fr: "Som Tam Chada d'Or",
      en: "Golden Chada Som Tam",
      th: "ส้มตำไทยไข่เค็มจักรพรรดิ",
      de: "Goldene Chada Som Tam",
      es: "Som Tam Chada Dorado",
      it: "Som Tam Chada d'Oro",
      pt: "Som Tam Chada de Ouro",
      zh: "金冠金丝木瓜沙拉",
      ja: "御料ソムタム",
      ko: "골든 차다 솜땀",
    },
    description: {
      fr: "Salade de papaye verte pilée à la minute, piment oiseau, lime fraîche, sucre de fleur de coco et cacahuètes torréfiées.",
      en: "Green papaya shredded to order and pestled with bird's eye chili, fresh key lime, coconut flower nectar, and dry-roasted peanuts.",
      th: "ส้มตำมะละกอเส้นสับมือสดใหม่ ตำครกดินเผาร่วมกับพริกขี้หนูสวน น้ำมะนาวแท้ น้ำตาลดอกมะพร้าว และถั่วลิสงคั่วเกลืออุ่นๆ",
      de: "Frisch zubereiteter grüner Papayasalat mit Chili, frischer Limette, Kokosblütenzucker und gerösteten Erdnüssen.",
      es: "Ensalada de papaya verde rallada al momento, chiles de árbol, jugo de lima artesanal, azúcar de coco y cacahuetes tostados.",
      it: "Insalata di papaya verde pestata al momento, peperoncini thai, lime fresco, zucchero di palma e arachidi tostate.",
      pt: "Salada de papaia verde ralada na hora, malaguetas, sumo de lima fresco, açúcar de coco e amendoins torrados.",
      zh: "冷碟爽嫩青木瓜丝，古法木臼捣制，搭配朝天椒、鲜榨青柠汁、纯椰糖和极香烤花生碎。",
      ja: "ご注文ごとに削りだす青パパイヤ、タイトウガラシ、最高級ヤシ蜜、煎りたて落花生のお口弾ける激辛サラダ。",
      ko: "주문 즉시 손으로 가늘게 채 썰어 빻은 아삭아삭한 그린 파파야, 매콤한 프릭키누 고추, 꽃 코코넛 시럽, 볶은 땅콩의 건강한 만남.",
    },
    price: 18,
    image: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=800&q=80",
    isSpicy: true,
    spicyLevel: 3,
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
    tags: ["all", "spiced", "vegetarian", "vegan", "gluten-free"],
  },
  {
    id: "pad_kra_prow",
    name: {
      fr: "Poulet Sauté au Basilic Sacré",
      en: "Holy Basil Minced Chicken",
      th: "ผัดกะเพราไก่บ้านไข่ดาวกรอบ",
      de: "Gebratenes Hähnchen mit heiligem Basilikum",
      es: "Pollo Salteado con Albahaca Sagrada",
      it: "Pollo con Basilico Sacro",
      pt: "Frango com Manjericão Sagrado",
      zh: "打抛香叶炒走地鸡肉",
      ja: "ガパオライス地鶏の聖なるバジル炒め",
      ko: "홀리 바질 치킨 덮밥",
    },
    description: {
      fr: "Poulet fermier haché sauvagement au couteau, sauté au wok à feu vif avec du basilic thaï sacré (Kra Prow) et des piments.",
      en: "Free-range chicken minced on the block, flash-wokked with extremely aromatic Holy Basil leaves and sizzling peppers.",
      th: "กะเพราไก่สับด้วยมือ ผัดไฟแดงร้อนแรง คั่วใบกะเพราป่าสีแดงมีกลิ่นหอมแรง และพริกขี้หนูแห้ง เสิร์ฟพร้อมไข่ดาวกรอบฟูน้ำยิ้ม",
      de: "Gehacktes Freilandhühnchen mit dem Messer scharf im Wok angebraten mit sehr aromatischen heiligen Basilikumblättern und Chili.",
      es: "Pollo picado salteado en wok a fuego alto con hojas perfumadas de albahaca sagrada tailandesa y chiles crujientes.",
      it: "Pollo tritato saltato a fuoco vivo nel wok con foglie profumatissime di basilico sacro e peperoncino ardente.",
      pt: "Frango picado salteado no wok com folhas aromáticas de manjericão sagrado e malaguetas ardentes.",
      zh: "手剁爽口走地鸡肉，高温重火翻炒，锁住打抛叶辛香与鲜辣椒香。",
      ja: "包丁で叩いた贅沢地鶏肉、タイの神聖なホーリーバジル（ガパオ）、激辛唐辛子を強火の油で一気に煽った本場ガパオ炒め。",
      ko: "칼로 직접 잘게 다진 무항생제 프리미엄 닭고기, 강한 불로 웍에서 볶아내어 알싸한 홀리 바질 향이 일품인 타이 대중 건강식.",
    },
    price: 24,
    image: "https://images.unsplash.com/photo-1562967914-608f82629710?auto=format&fit=crop&w=800&q=80",
    isSpicy: true,
    spicyLevel: 2,
    tags: ["all", "spiced", "chicken"],
  },
  {
    id: "seafood_chili",
    name: {
      fr: "Trésor de l'Andaman au Piment Doux",
      en: "Andaman Sea Sweet Chili Sizzler",
      th: "ทะเลรวมมิตรผัดพริกเผาชาววัง",
      de: "Meeresfrüchte aus der Andamanensee im Wok",
      es: "Mariscos del Mar de Andamán al Wok",
      it: "Frutti di Mare del Mare di Andamane",
      pt: "Mariscos do Mar de Andaman no Wok",
      zh: "安达曼海珍美香辣海鲜",
      ja: "アンダマン海鮮チリ炒め",
      ko: "안다만 해산물 칠리 볶음",
    },
    description: {
      fr: "Médaillon de homard, noix de Saint-Jacques royales et calmars poêlés, agrémentés de purée de chili rôti fait maison.",
      en: "Glistening scallops, fresh lobster medallion, and tender calamari seared to perfection and tossed in rich toasted chili paste.",
      th: "กุ้งแม่น้ำ หอยเชลล์ฮอกไกโด และปลาหมึกสดเนื้อเด้ง ผัดซอสพริกเผาสูตรลับชาววัง โรยพริกไทยอ่อนและใบโหระพา",
      de: "Frische Jakobsmuscheln, Hummermedaillons und zarter Tintenfisch, perfekt gebraten und in hausgemachter Chilipaste geschwenkt.",
      es: "Vieras tiernas, medallón de langosta fresca y calamar salteados a la perfección con pasta de chiles ahumados de la casa.",
      it: "Capesante prelibate, medaglione di astice e calamari saltati con purea di peperoncino tostato e basilico dolce.",
      pt: "Vieiras frescas, medalhão de lagosta e lula salteados com pasta caseira de malaguetas assadas e manjericão.",
      zh: "精选新鲜贝肉、龙虾球以及Q弹乌贼，裹满主厨自制碳烤香浓辣椒酱，满口鲜甜微辣。",
      ja: "新鮮なホタテ、ロブスター、イカのアジアンハーブ焼き、香ばしい特製チリペーストソースをたっぷり絡めて。",
      ko: "통통한 완자와 바닷가재 살, 쫄깃한 한치를 구워 깊은 풍미의 수제 화로 칠리 오일 및 야채와 볶은 요리.",
    },
    price: 35,
    image: "https://images.unsplash.com/photo-1534080391025-09795d197360?auto=format&fit=crop&w=800&q=80",
    isSpicy: true,
    spicyLevel: 1,
    tags: ["all", "spiced", "seafood"],
  },
  {
    id: "mango_sticky_rice",
    name: {
      fr: "Riz Gluant à la Mangue & Pandan Royal",
      en: "Royal Pandan Mango Sticky Rice",
      th: "ข้าวเหนียวมะม่วงสวนหลวงเปียกใบเตย",
      de: "Königlicher Pandan Mango Sticky Rice",
      es: "Arroz con Leche de Coco, Mango y Pandano",
      it: "Mango Sticky Rice al Pandano Reale",
      pt: "Arroz Doce de Coco com Manga e Pandano",
      zh: "斑斓叶香芒果糯米饭",
      ja: "王宮風マンゴーともち米デザート",
      ko: "로열 판단 망고 스티키 라이스",
    },
    description: {
      fr: "Mangues mûres sucrées importées du Siam, riz gluant parfumé à la feuille de pandan et arrosé de nectar de coco tiède.",
      en: "Sweet golden mango slices imported straight from Thailand, sweet sticky rice infused with pandan, and rich warm coconut milk glaze.",
      th: "มะม่วงน้ำดอกไม้หวานฉ่ำคัดพิเศษ ทานคู่กับข้าวเหนียวเขี้ยวงูมูลกะทิหอมใบเตย โรยถั่วทองทอดกรอบสีเหลืองทอง",
      de: "Süße goldene Mangoscheiben importiert aus Siam, klebriger Duftreis mit Pandan-Aroma und warmer Kokosmilchglasur.",
      es: "Mangos dulces maduros importados de Siam, arroz gluant perfumado con hoja de pandano y bañado en deliciosa leche de coco tibia.",
      it: "Fette di mango dolce dorato, riso glutinoso cotto a vapore nel latte di cocco con essenza di pandano.",
      pt: "Fatias de manga dourada doce, arroz glutinoso infundido com pandano e regado com leite de coco quente.",
      zh: "暹罗空运黄金香甜芒果肉，配以纯天然斑斓汁蒸煮的弹牙糯米饭，浇淋椰浆和炸豆仁。",
      ja: "タイ直輸入の甘熟ゴールデンマンゴー、パンダンリーフで香りづけした温かい特製もち米に濃厚なココナッツミルクソース掛け。",
      ko: "태국 산지 직송 무르익은 노란 망고와 판단 잎 향을 머금은 쫀득한 찹쌀밥, 달콤하고 따뜻한 원액 코코넛 소스.",
    },
    price: 16,
    image: "https://images.unsplash.com/photo-1563729784474-d77dbb933a9e?auto=format&fit=crop&w=800&q=80",
    isSpicy: false,
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
    tags: ["all", "non-spiced", "vegetarian", "vegan", "gluten-free", "desserts"],
  },
  {
    id: "thai_tea",
    name: {
      fr: "Cha Yen Thaïlandais aux Épices",
      en: "Spiced Thai Cha Yen",
      th: "ชาไทยเย็นสูตรโบราณเข้มข้น",
      de: "Klassischer Eistee Cha Yen",
      es: "Té Frío Cha Yen Estilo Tailandés",
      it: "Tè Freddo Cha Yen Thailandese",
      pt: "Chá Gelado Cha Yen Tailandês",
      zh: "手煮冰镇丝滑泰式奶茶",
      ja: "自家製淹れたてタイミルクティー",
      ko: "수제 아이스 타밀크티",
    },
    description: {
      fr: "Thé noir thaïlandais infusé à la badiane et cannelle, sucré au lait concentré crémeux et servi sur glace pilée.",
      en: "Slow-brewed traditional Thai black tea spiced with star anise and cinnamon, sweetened with organic condensed milk.",
      th: "ชาไทยใส่นมคั้นเย็น ชงเข้มข้นกลิ่นชาคั่วโบราณ กลิ่นอบเชยเทศและดอกจันทน์ หวานมันกลมกล่อมกำลังดี",
      de: "Langsam gebrühter thailändischer Schwarztee mit Sternanis und Zimt, verfeinert mit cremiger Kondensmilch über Crushed Ice.",
      es: "Té negro tailandés infusionado con anís estrellado y canela, endulzado con leche condensada cremosa sobre hielo picado.",
      it: "Tè nero thailandese tradizionale con anice stellato e cannella, dolcificato con latte condensato cremoso.",
      pt: "Chá preto tradicional tailandês com anis estrelado e canela, adoçado com leite condensado cremoso.",
      zh: "传统手工拉制红茶，加入八角与肉桂，淋入顺滑炼乳，配以碎冰。",
      ja: "スターアニス（八角）とシナモンを煮出し、濃厚なコンデンスミルクをたっぷり注いだクラシックな特製極細アイスティー。",
      ko: "팔각과 시나몬으로 우려낸 태국산 프리미엄 홍차에 유기농 연유와 얼음을 띄워 극강의 부드러움을 선사하는 국민 음료.",
    },
    price: 8,
    image: "https://images.unsplash.com/photo-1534080391025-09795d197360?auto=format&fit=crop&w=800&q=80",
    isSpicy: false,
    isVegetarian: true,
    isGlutenFree: true,
    tags: ["all", "non-spiced", "vegetarian", "drinks"],
  },
];

export const GALLERY_THAILAND = [
  {
    url: "https://images.unsplash.com/photo-1528127269322-539801943592?auto=format&fit=crop&w=600&q=80",
    title: { fr: "Bangkok Majestueuse", en: "Majestic Bangkok" },
  },
  {
    url: "https://images.unsplash.com/photo-1508009603885-50cf7c579365?auto=format&fit=crop&w=600&q=80",
    title: { fr: "Marchés Flottants", en: "Floating Markets" },
  },
  {
    url: "https://images.unsplash.com/photo-1552465011-b4e21bf6e79a?auto=format&fit=crop&w=600&q=80",
    title: { fr: "Plages d'Andaman", en: "Andaman Beaches" },
  },
  {
    url: "https://images.unsplash.com/photo-1583089892943-e02e5b017b6a?auto=format&fit=crop&w=600&q=80",
    title: { fr: "Monuments Sacrés", en: "Sacred Monuments" },
  },
];

export const GALLERY_SOUVENIRS = [
  {
    url: "https://images.unsplash.com/photo-1464802686167-b939a6910659?auto=format&fit=crop&w=600&q=80",
    title: { fr: "Lumières de Chiang Mai", en: "Chiang Mai Lanterns" },
  },
  {
    url: "https://images.unsplash.com/photo-1583089892943-e02e5b017b6a?auto=format&fit=crop&w=600&q=80",
    title: { fr: "Soie Impériale", en: "Imperial Silk Craft" },
  },
  {
    url: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=600&q=80",
    title: { fr: "Artisanat du Bambou", en: "Bamboo Woodcraft" },
  },
  {
    url: "https://images.unsplash.com/photo-1528127269322-539801943592?auto=format&fit=crop&w=600&q=80",
    title: { fr: "Temples Millénaires", en: "Millenary Ruins" },
  },
];

export const MOCK_REVIEWS: Review[] = [
  {
    id: "rev_1",
    author: "Viscomte de Valois",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=150&q=80",
    rating: 5,
    date: "2026-05-18",
    comment: {
      fr: "Un voyage direct à Chiang Mai. Le curry vert aux herbes fraîches est une révélation d'arômes, d'une onctuosité royale.",
      en: "A direct trip to Chiang Mai. The green curry with fresh herbs is an absolute revelation of fine royal creaminess.",
      th: "เหมือนเดินทางไปเชียงใหม่โดยตรง แกงเขียวหวานสมุนไพรสดคือที่สุดของกลิ่นอายและความหอมมันระดับชาววัง",
    },
    tag: "Expérience Royale",
  },
  {
    id: "rev_2",
    author: "Sir Robert Sterling",
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=150&q=80",
    rating: 5,
    date: "2026-05-24",
    comment: {
      fr: "Exceptionnel. L'élégance de la décoration florale, le service digne d'un hôtel 5 étoiles et ce bœuf Wagyu d'un fondant divin.",
      en: "Outstanding. The elegance of botanical dome décor, the 5-star hotel concierge service, and that incredibly tender Wagyu beef.",
      th: "ยอดเยี่ยมมาก ความงดงามของการตกแต่งแบบโดมธรรมชาติ การบริการประดุจโรงแรมห้าดาว และเนื้อวากิวที่ละลายในปากอย่างชวนฝัน",
    },
    tag: "Palace Culinaire",
  },
  {
    id: "rev_3",
    author: "Malika Al-Maktoum",
    avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=150&q=80",
    rating: 5,
    date: "2026-06-01",
    comment: {
      fr: "Le dîner en salon VIP royal était hors du temps. La vue sur les cuisines et la dégustation du dessert à la mangue sont irréprochables.",
      en: "Dining in the royal VIP salon was purely timeless. The view of the showcase kitchen and the mango sticky rice dessert are pristine.",
      th: "การรับประทานอาหารในคลับห้องรับรองวีไอพีให้ความรู้สึกประทับใจเป็นพิเศษ การชมครัวเปิดและเมนูของหวานมะม่วงนั้นไร้ที่ติอย่างแท้จริง",
    },
    tag: "Raffinement Suprême",
  },
];

export const FAQS: FAQItem[] = [
  {
    id: "faq_1",
    question: {
      fr: "Quels sont vos engagements sur l'authenticité des ingrédients ?",
      en: "What are your commitments regarding ingredient authenticity?",
    },
    answer: {
      fr: "Nous importons directement par fret aérien bi-hebdomadaire toutes nos herbes aromatiques, citrons kaffir, et piments de fermes artisanales certifiées de Chiang Mai pour assurer une authenticité totale.",
      en: "We import directly via premium bi-weekly air freight all our fresh spices, kaffir limes, and bird's eye chilies from certified Chiang Mai micro-farms.",
    },
  },
  {
    id: "faq_2",
    question: {
      fr: "Proposez-vous des options végétariennes, sans gluten ou adaptées aux allergies ?",
      en: "Do you offer vegetarian, vegan, and allergy-friendly curation?",
    },
    answer: {
      fr: "Oui, notre menu intelligent est entièrement filtrable. Nos currys traditionnels et desserts sont naturellement sans gluten et à base de lait de coco biologique.",
      en: "Yes, our smart interactive cards are totally filterable. Traditional curries and plant desserts are naturally organic-coconut based and gluten-free.",
    },
  },
  {
    id: "faq_3",
    question: {
      fr: "Peut-on privatiser le dôme végétal pour des événements privés ?",
      en: "Is privatization of the botanical domes available for groups?",
    },
    answer: {
      fr: "Absolument. Nous disposons de salons privés royaux et du dôme tropical central, modulables jusqu'à 80 convives, avec majordome dédié.",
      en: "Absolutely. We offer customized private dining in our Royal Pavilion and botanical dome accommodating up to 80 guests with matching host service.",
    },
  },
];

export const MOCK_TABLES: Table[] = [
  { id: "tab_1", name: "Dôme Royal Orchid 1", capacity: 4, status: "available", x: 15, y: 25, type: "royal" },
  { id: "tab_2", name: "Dôme Royal Orchid 2", capacity: 6, status: "available", x: 45, y: 20, type: "royal" },
  { id: "tab_3", name: "Salon Chiang Mai Sunset", capacity: 2, status: "available", x: 18, y: 65, type: "romantic" },
  { id: "tab_4", name: "Terrasse Lotus Garden 1", capacity: 2, status: "reserved", x: 80, y: 30, type: "terrace" },
  { id: "tab_5", name: "Terrasse Lotus Garden 2", capacity: 4, status: "available", x: 82, y: 60, type: "terrace" },
  { id: "tab_6", name: "Salon Bann Thai Familial", capacity: 8, status: "available", x: 48, y: 68, type: "family" },
];

export const TRANSLATE_DICTIONARY: { [key: string]: { [key: string]: string } } = {
  welcome: {
    fr: "Découvrez les saveurs authentiques de la Thaïlande",
    en: "Discover the authentic flavors of Thailand",
    th: "สัมผัสรสชาติไทยแท้ดั้งเดิมและหรูหรา",
    de: "Entdecken Sie die authentischen Aromen Thailands",
    es: "Descubre los sabores auténticos de Tailandia",
    it: "Scopri gli autentici sapori della Thailandia",
    pt: "Descubra os sabores autênticos da Tailândia",
    zh: "探索泰国的纯正风味",
    ja: "タイの本格的な味わいを発見する",
    ko: "태국의 정통 풍미를 만나보세요",
  },
  tagline: {
    fr: "Une expérience culinaire unique où tradition, passion et hospitalité se rencontrent.",
    en: "A flawless dining retreat combining time-honored recipe crafts and Siamese warmth.",
    th: "ประสบการณ์อาหารชั้นเลิศที่ผสานขนบธรรมเนียม ความรัก และการต้อนรับที่สมบูรณ์แบบ",
  },
  bookNow: {
    fr: "Réserver une table",
    en: "Book a Table",
    th: "สำรองที่นั่ง",
    de: "Tisch belegen",
    es: "Reservar mesa",
    it: "Prenota tavolo",
    pt: "Reservar mesa",
    zh: "预订宴席",
    ja: "テーブル予約",
    ko: "예약하기",
  },
  orderNow: {
    fr: "Commander en Ligne",
    en: "Order Online",
    th: "สั่งอาหารออนไลน์",
    de: "Online bestellen",
    es: "Pedir en línea",
    it: "Ordina in linea",
    pt: "Pedir online",
    zh: "在线订购",
    ja: "オンライン注文",
    ko: "온라인 결제",
  },
  ourStoryTitle: {
    fr: "Notre Héritage",
    en: "Our Story",
    th: "มรดกของเรา",
  },
  specialtiesTitle: {
    fr: "Nos Chefs-d'Œuvres Gastrononomiques",
    en: "Our Culinary Masterpieces",
    th: "เมนูพิเศษยอดนิยม",
  },
  menuIntelligentTitle: {
    fr: "Menu Interactif & Recherche Haute Définition",
    en: "Smart Menu Curation & Real-Time Search",
    th: "เมนูอัจฉริยะและการค้นหาทันที",
  },
  reviewsTitle: {
    fr: "L'Écho de Nos Hôtes Privilégiés",
    en: "Echoes of Our Distinguished Guests",
    th: "รีวิวจากลูกค้าคนสำคัญ",
  },
  faqTitle: {
    fr: "Secrets & Informations Royales",
    en: "Royal Information & Secrets",
    th: "คำถามที่พบบ่อย",
  },
  digitalConciergeTitle: {
    fr: "Concierge Digital & Visite 360°",
    en: "Digital Concierge & 360° Room Tour",
    th: "ผู้ช่วยดิจิทัลและการเที่ยวชม 360 องศา",
  },
};
